version: '3'
services: 
  example_service:
    build:
      context: .
      args:
      - path_to_service=services/simple-express-server
    environment:
      NODE_ENV: development
    volumes:
    - "./services/simple-express-server:/usr/src/app"
    - "./node_modules:/usr/src/app/node_modules"
    - "./packages:/usr/src/app/packages"
    ports:
    - "3000:3000"